create table if not exists EVENT (
    ID UUID NOT NULL DEFAULT uuid_generate_v4 (),
    NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    DATE DATE NOT NULL,
    PRODUCER UUID NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (PRODUCER) REFERENCES PRODUCER(ID)
);